# Generated by Django 4.1.6 on 2023-03-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_alter_businesssystem_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesssystem",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
