# Generated by Django 4.1.6 on 2023-03-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_alter_businesssystem_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="time_of_attendance",
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
    ]
