# Generated by Django 4.1.6 on 2023-03-31 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_remove_student_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="student", name="posted_by",),
    ]
