# Generated by Django 4.1.6 on 2023-03-31 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_remove_student_contact_no_remove_student_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamreviewroom",
            name="room",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="pages.room"
            ),
        ),
    ]
