# Generated by Django 4.1.6 on 2023-03-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_alter_teamreviewroom_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="number",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
